version: 2

models:
  - name: int_daily_sales
    description: "日別売上集計の中間モデル"
    columns:
      - name: vending_machine_id
        description: "自動販売機ID"
        tests:
          - not_null
      - name: location_name
        description: "設置場所名"
        tests:
          - not_null
      - name: product_name
        description: "商品名"
        tests:
          - not_null
      - name: category_name
        description: "カテゴリ名"
        tests:
          - not_null
      - name: payment_method_name
        description: "決済方法名"
        tests:
          - not_null
      - name: purchase_date
        description: "購入日"
        tests:
          - not_null
      - name: sales_count
        description: "売上件数"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: total_sales_amount
        description: "売上金額合計"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: int_current_stock
    description: "現在在庫の中間モデル"
    columns:
      - name: vending_machine_id
        description: "自動販売機ID"
        tests:
          - not_null
      - name: location_name
        description: "設置場所名"
        tests:
          - not_null
      - name: product_id
        description: "商品ID"
        tests:
          - not_null
      - name: product_name
        description: "商品名"
        tests:
          - not_null
      - name: category_name
        description: "カテゴリ名"
        tests:
          - not_null
      - name: current_stock
        description: "現在在庫数"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: int_sales_performance
    description: "売上パフォーマンス分析の中間モデル"
    columns:
      - name: vending_machine_id
        description: "自動販売機ID"
        tests:
          - not_null
      - name: product_id
        description: "商品ID"
        tests:
          - not_null
      - name: total_sales_count
        description: "総売上件数"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: total_revenue
        description: "総売上金額"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: int_replenishment_analysis
    description: "補充分析の中間モデル"
    columns:
      - name: vending_machine_id
        description: "自動販売機ID"
        tests:
          - not_null
      - name: product_id
        description: "商品ID"
        tests:
          - not_null
      - name: replenishment_count
        description: "補充回数"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: total_replenishment_quantity
        description: "総補充数量"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: int_data_quality_summary
    description: "データ品質サマリの中間モデル"
    columns:
      - name: table_name
        description: "テーブル名"
        tests:
          - not_null
      - name: error_level
        description: "エラーレベル"
        tests:
          - not_null
          - accepted_values:
              values: ['FATAL', 'ERROR', 'WARNING', 'INFO']
      - name: error_count
        description: "エラー件数"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0