version: 2

models:
  - name: stg_vending_machines
    description: "自動販売機マスターのステージングテーブル"
    columns:
      - name: vending_machine_id
        description: "自動販売機ID"
        tests:
          - not_null
          - unique
      - name: location_name
        description: "設置場所"
        tests:
          - not_null

  - name: stg_products
    description: "商品マスターのステージングテーブル"
    columns:
      - name: product_id
        description: "商品ID"
        tests:
          - not_null
          - unique
      - name: product_name
        description: "商品名"
        tests:
          - not_null
      - name: price
        description: "販売価格（円）"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: stg_sales
    description: "売上実績のステージングテーブル"
    columns:
      - name: sales_id
        description: "売上ID"
        tests:
          - not_null
          - unique
      - name: sales_amount
        description: "売上金額（投入金額 - お釣り）"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: stg_replenishments
    description: "補充実績のステージングテーブル"
    columns:
      - name: replenishment_id
        description: "補充ID"
        tests:
          - not_null
          - unique
      - name: replenishment_quantity
        description: "補充数量"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1