version: 2

models:
  - name: stg_vending_machines
    description: "ステージング：自動販売機マスタデータ"
    columns:
      - name: vending_machine_id
        description: "自動販売機ID"
        tests:
          - not_null
          - unique

  - name: stg_product_categories
    description: "ステージング：商品カテゴリマスタデータ"
    columns:
      - name: product_category_id
        description: "商品カテゴリID"
        tests:
          - not_null
          - unique
      - name: category_name
        description: "カテゴリ名"
        tests:
          - not_null

  - name: stg_products
    description: "ステージング：商品マスタデータ"
    columns:
      - name: product_id
        description: "商品ID"
        tests:
          - not_null
          - unique
      - name: product_category_id
        description: "商品カテゴリID"
        tests:
          - not_null
          - relationships:
              to: ref('stg_product_categories')
              field: product_category_id
      - name: product_name
        description: "商品名"
        tests:
          - not_null
      - name: price
        description: "価格"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: stg_staff
    description: "ステージング：担当者マスタデータ"
    columns:
      - name: staff_id
        description: "担当者ID"
        tests:
          - not_null
          - unique

  - name: stg_payment_methods
    description: "ステージング：決済方法マスタデータ"
    columns:
      - name: payment_method_id
        description: "決済方法ID"
        tests:
          - not_null
          - unique

  - name: stg_sales
    description: "ステージング：売上データ"
    columns:
      - name: sales_id
        description: "売上ID（サロゲートキー）"
        tests:
          - not_null
          - unique
      - name: vending_machine_id
        description: "自動販売機ID"
        tests:
          - not_null
          - relationships:
              to: ref('stg_vending_machines')
              field: vending_machine_id
      - name: product_id
        description: "商品ID"
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: purchase_datetime
        description: "購入日時"
        tests:
          - not_null
      - name: payment_method_id
        description: "決済方法ID"
        tests:
          - not_null
          - relationships:
              to: ref('stg_payment_methods')
              field: payment_method_id
      - name: input_amount
        description: "投入金額"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: change_amount
        description: "お釣り金額"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: stg_replenishments
    description: "ステージング：補充記録データ"
    columns:
      - name: replenishment_id
        description: "補充ID（サロゲートキー）"
        tests:
          - not_null
          - unique
      - name: vending_machine_id
        description: "自動販売機ID"
        tests:
          - not_null
          - relationships:
              to: ref('stg_vending_machines')
              field: vending_machine_id
      - name: product_id
        description: "商品ID"
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: replenishment_datetime
        description: "補充日時"
        tests:
          - not_null
      - name: replenishment_quantity
        description: "補充数量"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
      - name: stock_before
        description: "補充前在庫数"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      - name: stock_after
        description: "補充後在庫数"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0