version: 2

sources:
  - name: raw_vending_machine_data
    description: "自動販売機システムの生データソース"
    tables:
      - name: mst_vending_machine
        description: "自動販売機マスター"
        columns:
          - name: vending_machine_id
            description: "自動販売機ID"
            tests:
              - not_null
              - unique
          - name: location_name
            description: "設置場所"
            tests:
              - not_null
          - name: installation_date
            description: "設置日"
            tests:
              - not_null
          - name: created_at
            description: "作成日時"
            tests:
              - not_null
          - name: updated_at
            description: "更新日時"
            tests:
              - not_null

      - name: mst_product_category
        description: "商品カテゴリマスター"
        columns:
          - name: product_category_id
            description: "商品カテゴリID"
            tests:
              - not_null
              - unique
          - name: category_name
            description: "カテゴリ名"
            tests:
              - not_null
              - unique
          - name: created_at
            description: "作成日時"
            tests:
              - not_null
          - name: updated_at
            description: "更新日時"
            tests:
              - not_null

      - name: mst_product
        description: "商品マスター"
        columns:
          - name: product_id
            description: "商品ID"
            tests:
              - not_null
              - unique
          - name: product_category_id
            description: "商品カテゴリID"
            tests:
              - not_null
              - relationships:
                  to: source('raw_vending_machine_data', 'mst_product_category')
                  field: product_category_id
          - name: product_name
            description: "商品名"
            tests:
              - not_null
          - name: price
            description: "販売価格（円）"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
          - name: created_at
            description: "作成日時"
            tests:
              - not_null
          - name: updated_at
            description: "更新日時"
            tests:
              - not_null

      - name: mst_payment_method
        description: "決済方法マスター"
        columns:
          - name: payment_method_id
            description: "決済方法ID"
            tests:
              - not_null
              - unique
          - name: payment_method_name
            description: "決済方法名"
            tests:
              - not_null
              - unique
          - name: created_at
            description: "作成日時"
            tests:
              - not_null
          - name: updated_at
            description: "更新日時"
            tests:
              - not_null

      - name: mst_staff
        description: "スタッフマスター"
        columns:
          - name: staff_id
            description: "スタッフID"
            tests:
              - not_null
              - unique
          - name: staff_name
            description: "スタッフ名"
            tests:
              - not_null

      - name: fact_sales
        description: "売上実績"
        columns:
          - name: sales_id
            description: "売上ID（サロゲートキー）"
            tests:
              - not_null
              - unique
          - name: vending_machine_id
            description: "自動販売機ID"
            tests:
              - not_null
              - relationships:
                  to: source('raw_vending_machine_data', 'mst_vending_machine')
                  field: vending_machine_id
          - name: product_id
            description: "商品ID"
            tests:
              - not_null
              - relationships:
                  to: source('raw_vending_machine_data', 'mst_product')
                  field: product_id
          - name: purchase_datetime
            description: "購入日時"
            tests:
              - not_null
          - name: payment_method_id
            description: "決済方法ID"
            tests:
              - not_null
              - relationships:
                  to: source('raw_vending_machine_data', 'mst_payment_method')
                  field: payment_method_id
          - name: input_amount
            description: "投入金額（円）"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
          - name: change_amount
            description: "お釣り金額（円）"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
          - name: created_at
            description: "作成日時"
            tests:
              - not_null

      - name: fact_replenishment
        description: "商品補充実績"
        columns:
          - name: replenishment_id
            description: "補充ID（サロゲートキー）"
            tests:
              - not_null
              - unique
          - name: vending_machine_id
            description: "自動販売機ID"
            tests:
              - not_null
              - relationships:
                  to: source('raw_vending_machine_data', 'mst_vending_machine')
                  field: vending_machine_id
          - name: product_id
            description: "商品ID"
            tests:
              - not_null
              - relationships:
                  to: source('raw_vending_machine_data', 'mst_product')
                  field: product_id
          - name: replenishment_datetime
            description: "補充日時"
            tests:
              - not_null
          - name: replenishment_quantity
            description: "補充数量"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 1
          - name: stock_before
            description: "補充前在庫数"
            tests:
              - dbt_utils.accepted_range:
                  min_value: 0
          - name: stock_after
            description: "補充後在庫数"
            tests:
              - dbt_utils.accepted_range:
                  min_value: 0
          - name: staff_id
            description: "補充担当者ID"
            tests:
              - relationships:
                  to: source('raw_vending_machine_data', 'mst_staff')
                  field: staff_id
          - name: created_at
            description: "作成日時"
            tests:
              - not_null